"""
Generated by Statechart compiler by Glenn De Jonghe, Joeri Exelmans, Simon Van Mierlo, and Yentl Van Tendeloo (for the inspiration)

Model author: Francisco Simoes
Model name:   Counter

"""

from python_sccd.python_sccd_runtime.statecharts_core import *
from sccd.runtime.statecharts_core import *
from colors import *
import argparse
from sccd.compiler.utils import FileWriter
import os

# package "Counter"

class MainApp(RuntimeClassBase):
    def __init__(self, controller):
        RuntimeClassBase.__init__(self, controller)
        
        self.semantics.big_step_maximality = StatechartSemantics.TakeMany
        self.semantics.internal_event_lifeline = StatechartSemantics.Queue
        self.semantics.input_event_lifeline = StatechartSemantics.FirstComboStep
        self.semantics.priority = StatechartSemantics.SourceParent
        self.semantics.concurrency = StatechartSemantics.Single
        
        self.firstTime = True
        self.didCalcs = Queue()
        self.active_states = Queue()
        self.startTime = 0.0
        self.executionTime = 0.0
        self.localExecutionTime = 0.0
        self.cumulativeDebugTime = 0.0
        self.tracedEvents = []
        self.expiredTimestamps = []
        
        # set execution speed
        self.setSimulationSpeed()
        
        # build Statechart structure
        self.build_statechart_structure()
        
        # user defined attributes
        self.counter = 0
        
        # call user defined constructor
        MainApp.user_defined_constructor(self)
    
    def user_defined_constructor(self):
        pass
    
    def setSimulationSpeed(self):
        
        parser = argparse.ArgumentParser(prog="python -m sccd.compiler.sccdc")
        parser.add_argument('-s','--simType', help='Simulation type which has 3 different variations: 0 = default simulation, scale factor of 1; 1 = scaled real-time simulation, takes one extra arg to set the scale factor; 2 = as-fast-as-possible simulation, scale factor = infinity', default=0)
        parser.add_argument('-f','--factor', help='Scale factor: default value is 1; if the factor is 2, the simulation 2x faster', default=1)
        args = vars(parser.parse_args())
        
        if args['simType'] is not None:
            args['simType'] = float(args['simType'])
            args['factor'] = float(args['factor'])
            self.scaleFactor = 1.0
            if args['simType'] == 0:
                print(colors.fg.yellow+"Real-time Simulation")
            elif args['simType'] == 1:
                print(colors.fg.yellow+"Scaled Real-time Simulation")
                if args['factor'] is not None and args['factor'] > 0:
                    self.scaleFactor = args['factor']
            elif args['simType'] == 2:
                print(colors.fg.yellow+"As-fast-as-possible Simulation")
                self.scaleFactor = float('inf')
            else:
                print(colors.fg.yellow+"Invalid simulation type. Defaulting to Real-time Simulation")
                self.scaleFactor = 1.0
            print(colors.fg.yellow+"Scale Factor: {}".format(self.scaleFactor)+colors.reset)
    
    def user_defined_destructor(self):
        pass
    
    
    # user defined method
    def increment_counter(self):
        self.counter = self.counter + 1
    
    
    # builds Statechart structure
    def build_statechart_structure(self):
        
        # state <root>
        self.states[""] = State(0, "", self)
        
        # state /state_A
        self.states["/state_A"] = State(1, "/state_A", self)
        self.states["/state_A"].setEnter(self._state_A_enter)
        self.states["/state_A"].setExit(self._state_A_exit)
        
        # state /state_B
        self.states["/state_B"] = State(2, "/state_B", self)
        self.states["/state_B"].setEnter(self._state_B_enter)
        self.states["/state_B"].setExit(self._state_B_exit)
        
        # state /state_C
        self.states["/state_C"] = State(3, "/state_C", self)
        self.states["/state_C"].setEnter(self._state_C_enter)
        self.states["/state_C"].setExit(self._state_C_exit)
        
        # state /state_D
        self.states["/state_D"] = State(4, "/state_D", self)
        self.states["/state_D"].setEnter(self._state_D_enter)
        self.states["/state_D"].setExit(self._state_D_exit)
        
        # state /state_Debug
        self.states["/state_Debug"] = State(5, "/state_Debug", self)
        self.states["/state_Debug"].setEnter(self._state_Debug_enter)
        self.states["/state_Debug"].setExit(self._state_Debug_exit)
        
        # state /state_Final
        self.states["/state_Final"] = State(6, "/state_Final", self)
        self.states["/state_Final"].setEnter(self._state_Final_enter)
        
        # debug events
        pauseEvent = Event("pause", self.getInPortName("input"))
        stopEvent = Event("stop", self.getInPortName("input"))
        continueEvent = Event("continue", self.getInPortName("input"))
        
        # debug transitions
        self.pauseTransitions = {}
        self.timedTransitions = {}
        self.eventTransitions = {}
        self.createdTransitions = {}
        self.stopTransitions = {}
        self.timeBreakpointTransitions = {}
        self.genBreakpointTransitions = {}
        
        # add children
        self.states[""].addChild(self.states["/state_A"])
        self.states[""].addChild(self.states["/state_B"])
        self.states[""].addChild(self.states["/state_C"])
        self.states[""].addChild(self.states["/state_D"])
        self.states[""].addChild(self.states["/state_Debug"])
        self.states[""].addChild(self.states["/state_Final"])
        self.states[""].fixTree()
        self.states[""].default_state = self.states["/state_A"]
        
        # transition /state_A
        self.eventTransitions["/state_A"] = []
        self.timedTransitions["/state_A"] = []
        self.createdTransitions["/state_A"] = []
        self.timeBreakpointTransitions["/state_A"] = []
        self.genBreakpointTransitions["/state_A"] = []
        _state_A_0 = Transition(self, self.states["/state_A"], [self.states["/state_B"]])
        _state_A_0.setTrigger(Event("_0after"))
        self.states["/state_A"].addTransition(_state_A_0)
        self.timedTransitions["/state_A"].append(_state_A_0)
        _state_A_1 = Transition(self, self.states["/state_A"], [self.states["/state_C"]])
        _state_A_1.setTrigger(Event("_1after"))
        self.states["/state_A"].addTransition(_state_A_1)
        self.timedTransitions["/state_A"].append(_state_A_1)
        _state_A_2 = Transition(self, self.states["/state_A"], [self.states["/state_D"]])
        _state_A_2.setTrigger(Event("d", self.getInPortName("input")))
        self.states["/state_A"].addTransition(_state_A_2)
        self.eventTransitions["/state_A"].append(_state_A_2)
        
        # transition /state_B
        self.eventTransitions["/state_B"] = []
        self.timedTransitions["/state_B"] = []
        self.createdTransitions["/state_B"] = []
        self.timeBreakpointTransitions["/state_B"] = []
        self.genBreakpointTransitions["/state_B"] = []
        _state_B_0 = Transition(self, self.states["/state_B"], [self.states["/state_A"]])
        _state_B_0.setTrigger(Event("move", self.getInPortName("input")))
        self.states["/state_B"].addTransition(_state_B_0)
        self.eventTransitions["/state_B"].append(_state_B_0)
        
        # transition /state_C
        self.eventTransitions["/state_C"] = []
        self.timedTransitions["/state_C"] = []
        self.createdTransitions["/state_C"] = []
        self.timeBreakpointTransitions["/state_C"] = []
        self.genBreakpointTransitions["/state_C"] = []
        _state_C_0 = Transition(self, self.states["/state_C"], [self.states["/state_A"]])
        _state_C_0.setTrigger(Event("move", self.getInPortName("input")))
        self.states["/state_C"].addTransition(_state_C_0)
        self.eventTransitions["/state_C"].append(_state_C_0)
        
        # transition /state_D
        self.eventTransitions["/state_D"] = []
        self.timedTransitions["/state_D"] = []
        self.createdTransitions["/state_D"] = []
        self.timeBreakpointTransitions["/state_D"] = []
        self.genBreakpointTransitions["/state_D"] = []
        _state_D_0 = Transition(self, self.states["/state_D"], [self.states["/state_A"]])
        _state_D_0.setTrigger(Event("move", self.getInPortName("input")))
        self.states["/state_D"].addTransition(_state_D_0)
        self.eventTransitions["/state_D"].append(_state_D_0)
        
        # transitions /state_Debug
        # _state_A to /state_Debug
        _state_A_to_state_Debug = Transition(self, self.states["/state_A"], [self.states["/state_Debug"]])
        _state_A_to_state_Debug.setTrigger(pauseEvent)
        self.states["/state_A"].addTransition(_state_A_to_state_Debug)
        self.pauseTransitions["/state_A"] = _state_A_to_state_Debug
        
        # state_A from /state_Debug
        _state_Debug_to_state_A = Transition(self, self.states["/state_Debug"], [self.states["/state_A"]])
        _state_Debug_to_state_A.setTrigger(continueEvent)
        _state_Debug_to_state_A.setGuard(self.continueGuard_state_A)
        self.states["/state_Debug"].addTransition(_state_Debug_to_state_A)
        
        # _state_A to /state_Final
        _state_A_to_state_Final = Transition(self, self.states["/state_A"], [self.states["/state_Final"]])
        _state_A_to_state_Final.setTrigger(stopEvent)
        self.states["/state_A"].addTransition(_state_A_to_state_Final)
        self.stopTransitions["/state_A"] = _state_A_to_state_Final
        
        # _state_B to /state_Debug
        _state_B_to_state_Debug = Transition(self, self.states["/state_B"], [self.states["/state_Debug"]])
        _state_B_to_state_Debug.setTrigger(pauseEvent)
        self.states["/state_B"].addTransition(_state_B_to_state_Debug)
        self.pauseTransitions["/state_B"] = _state_B_to_state_Debug
        
        # state_B from /state_Debug
        _state_Debug_to_state_B = Transition(self, self.states["/state_Debug"], [self.states["/state_B"]])
        _state_Debug_to_state_B.setTrigger(continueEvent)
        _state_Debug_to_state_B.setGuard(self.continueGuard_state_B)
        self.states["/state_Debug"].addTransition(_state_Debug_to_state_B)
        
        # _state_B to /state_Final
        _state_B_to_state_Final = Transition(self, self.states["/state_B"], [self.states["/state_Final"]])
        _state_B_to_state_Final.setTrigger(stopEvent)
        self.states["/state_B"].addTransition(_state_B_to_state_Final)
        self.stopTransitions["/state_B"] = _state_B_to_state_Final
        
        # _state_C to /state_Debug
        _state_C_to_state_Debug = Transition(self, self.states["/state_C"], [self.states["/state_Debug"]])
        _state_C_to_state_Debug.setTrigger(pauseEvent)
        self.states["/state_C"].addTransition(_state_C_to_state_Debug)
        self.pauseTransitions["/state_C"] = _state_C_to_state_Debug
        
        # state_C from /state_Debug
        _state_Debug_to_state_C = Transition(self, self.states["/state_Debug"], [self.states["/state_C"]])
        _state_Debug_to_state_C.setTrigger(continueEvent)
        _state_Debug_to_state_C.setGuard(self.continueGuard_state_C)
        self.states["/state_Debug"].addTransition(_state_Debug_to_state_C)
        
        # _state_C to /state_Final
        _state_C_to_state_Final = Transition(self, self.states["/state_C"], [self.states["/state_Final"]])
        _state_C_to_state_Final.setTrigger(stopEvent)
        self.states["/state_C"].addTransition(_state_C_to_state_Final)
        self.stopTransitions["/state_C"] = _state_C_to_state_Final
        
        # _state_D to /state_Debug
        _state_D_to_state_Debug = Transition(self, self.states["/state_D"], [self.states["/state_Debug"]])
        _state_D_to_state_Debug.setTrigger(pauseEvent)
        self.states["/state_D"].addTransition(_state_D_to_state_Debug)
        self.pauseTransitions["/state_D"] = _state_D_to_state_Debug
        
        # state_D from /state_Debug
        _state_Debug_to_state_D = Transition(self, self.states["/state_Debug"], [self.states["/state_D"]])
        _state_Debug_to_state_D.setTrigger(continueEvent)
        _state_Debug_to_state_D.setGuard(self.continueGuard_state_D)
        self.states["/state_Debug"].addTransition(_state_Debug_to_state_D)
        
        # _state_D to /state_Final
        _state_D_to_state_Final = Transition(self, self.states["/state_D"], [self.states["/state_Final"]])
        _state_D_to_state_Final.setTrigger(stopEvent)
        self.states["/state_D"].addTransition(_state_D_to_state_Final)
        self.stopTransitions["/state_D"] = _state_D_to_state_Final
        
    
    def _state_A_enter(self):
        self.current_state = self.states["/state_A"]
        self.startTime = self.getSimulatedTime()
        
        while (not self.didCalcs.empty()):
            self.didCalcs.get()
        
        if self.firstTime == True:
            self.localExecutionTime = 0.0
            self.active_states.put(self.current_state)
            
            self.increment_counter();
            
            self.print_internal_state("/state_A")
            event = "entry: /state_A"
            allAttTuples = []
            allAttTuples.append(["counter", self.counter])
            self.saveEvent(event, self.getSimulatedTime(), allAttTuples)
            
            timers = []
            if self.scaleFactor != float("inf"):
                self.addTimer(0, 10 / self.scaleFactor)
                timers.append(10)
                self.addTimer(1, 20 / self.scaleFactor)
                timers.append(20)
                print((colors.fg.lightgreen + "Available Transition Options:") + colors.reset)
                self.process_time_transitions(timers, "/state_A")
            else:
                self.addTimer(0, 10.0 / self.scaleFactor)
            self.process_event_transitions("/state_A")
            
            print(colors.fg.lightgrey +"[/state_A] > "+colors.reset),
        else:
            self.addTimer(0, 10.0 - ((self.localExecutionTime / 1000.0) / self.scaleFactor))
            self.addTimer(1, 20.0 - ((self.localExecutionTime / 1000.0) / self.scaleFactor))
            event = "re-entry: /state_A"
            allAttTuples = []
            allAttTuples.append(["counter", self.counter])
            self.saveEvent(event, self.getSimulatedTime(), allAttTuples)
            print(colors.fg.lightgrey +"[/state_A] > "+colors.reset),
    
    def _state_A_exit(self):
        self.removeTimer(0)
        self.removeTimer(1)
        index = 2
        for et in self.expiredTimestamps:
            self.removeTimer(index)
            index = (index + 1)
        
        if self.didCalcs.empty():
            self.localExecutionTime = (self.localExecutionTime + (self.getSimulatedTime() - self.startTime))
            self.executionTime = (self.executionTime + (self.getSimulatedTime() - self.startTime))
            self.didCalcs.put(True)
        
        found = False
        for b in self.timeBreakpointTransitions["/state_A"]:
            if b.enabled_event != None:
                found = True
                timerIndex = int(b.enabled_event.name[1:2])
                startingIndex = 2
                self.expiredTimestamps[timerIndex - startingIndex] = True
        
        for b in self.genBreakpointTransitions["/state_A"]:
            if b.enabled_event != None:
                found = True
        
        if (self.pauseTransitions["/state_A"].enabled_event == None) and (not found):
            self.firstTime = True
            self.active_states.get()
        
        allTransitions = []
        allTransitions.extend(self.timedTransitions["/state_A"])
        allTransitions.extend(self.eventTransitions["/state_A"])
        allTransitions.extend(self.timeBreakpointTransitions["/state_A"])
        allTransitions.extend(self.genBreakpointTransitions["/state_A"])
        allTransitions.extend(self.createdTransitions["/state_A"])
        allTransitions.append(self.stopTransitions["/state_A"])
        allTransitions.append(self.pauseTransitions["/state_A"])
        event = "exit: /state_A"
        for tr in allTransitions:
            if not (tr.enabled_event == None):
                event = (event + (" - " + tr.enabled_event.name))
        allAttTuples = []
        allAttTuples.append(["counter", self.counter])
        self.saveEvent(event, self.getSimulatedTime(), allAttTuples)
    
    def _state_B_enter(self):
        self.current_state = self.states["/state_B"]
        self.startTime = self.getSimulatedTime()
        
        while (not self.didCalcs.empty()):
            self.didCalcs.get()
        
        if self.firstTime == True:
            self.localExecutionTime = 0.0
            self.active_states.put(self.current_state)
            
            self.increment_counter();
            
            self.print_internal_state("/state_B")
            event = "entry: /state_B"
            allAttTuples = []
            allAttTuples.append(["counter", self.counter])
            self.saveEvent(event, self.getSimulatedTime(), allAttTuples)
            print((colors.fg.lightgreen + "Available Transition Options:") + colors.reset)
            self.process_event_transitions("/state_B")
            
            print(colors.fg.lightgrey +"[/state_B] > "+colors.reset),
        else:
            event = "re-entry: /state_B"
            allAttTuples = []
            allAttTuples.append(["counter", self.counter])
            self.saveEvent(event, self.getSimulatedTime(), allAttTuples)
            print(colors.fg.lightgrey +"[/state_B] > "+colors.reset),
    
    def _state_B_exit(self):
        index = 2
        for et in self.expiredTimestamps:
            self.removeTimer(index)
            index = (index + 1)
        
        if self.didCalcs.empty():
            self.localExecutionTime = (self.localExecutionTime + (self.getSimulatedTime() - self.startTime))
            self.executionTime = (self.executionTime + (self.getSimulatedTime() - self.startTime))
            self.didCalcs.put(True)
        
        found = False
        for b in self.timeBreakpointTransitions["/state_B"]:
            if b.enabled_event != None:
                found = True
                timerIndex = int(b.enabled_event.name[1:2])
                startingIndex = 2
                self.expiredTimestamps[timerIndex - startingIndex] = True
        
        for b in self.genBreakpointTransitions["/state_B"]:
            if b.enabled_event != None:
                found = True
        
        if (self.pauseTransitions["/state_B"].enabled_event == None) and (not found):
            self.firstTime = True
            self.active_states.get()
        
        allTransitions = []
        allTransitions.extend(self.timedTransitions["/state_B"])
        allTransitions.extend(self.eventTransitions["/state_B"])
        allTransitions.extend(self.timeBreakpointTransitions["/state_B"])
        allTransitions.extend(self.genBreakpointTransitions["/state_B"])
        allTransitions.extend(self.createdTransitions["/state_B"])
        allTransitions.append(self.stopTransitions["/state_B"])
        allTransitions.append(self.pauseTransitions["/state_B"])
        event = "exit: /state_B"
        for tr in allTransitions:
            if not (tr.enabled_event == None):
                event = (event + (" - " + tr.enabled_event.name))
        allAttTuples = []
        allAttTuples.append(["counter", self.counter])
        self.saveEvent(event, self.getSimulatedTime(), allAttTuples)
    
    def _state_C_enter(self):
        self.current_state = self.states["/state_C"]
        self.startTime = self.getSimulatedTime()
        
        while (not self.didCalcs.empty()):
            self.didCalcs.get()
        
        if self.firstTime == True:
            self.localExecutionTime = 0.0
            self.active_states.put(self.current_state)
            
            self.increment_counter();
            
            self.print_internal_state("/state_C")
            event = "entry: /state_C"
            allAttTuples = []
            allAttTuples.append(["counter", self.counter])
            self.saveEvent(event, self.getSimulatedTime(), allAttTuples)
            print((colors.fg.lightgreen + "Available Transition Options:") + colors.reset)
            self.process_event_transitions("/state_C")
            
            print(colors.fg.lightgrey +"[/state_C] > "+colors.reset),
        else:
            event = "re-entry: /state_C"
            allAttTuples = []
            allAttTuples.append(["counter", self.counter])
            self.saveEvent(event, self.getSimulatedTime(), allAttTuples)
            print(colors.fg.lightgrey +"[/state_C] > "+colors.reset),
    
    def _state_C_exit(self):
        index = 2
        for et in self.expiredTimestamps:
            self.removeTimer(index)
            index = (index + 1)
        
        if self.didCalcs.empty():
            self.localExecutionTime = (self.localExecutionTime + (self.getSimulatedTime() - self.startTime))
            self.executionTime = (self.executionTime + (self.getSimulatedTime() - self.startTime))
            self.didCalcs.put(True)
        
        found = False
        for b in self.timeBreakpointTransitions["/state_C"]:
            if b.enabled_event != None:
                found = True
                timerIndex = int(b.enabled_event.name[1:2])
                startingIndex = 2
                self.expiredTimestamps[timerIndex - startingIndex] = True
        
        for b in self.genBreakpointTransitions["/state_C"]:
            if b.enabled_event != None:
                found = True
        
        if (self.pauseTransitions["/state_C"].enabled_event == None) and (not found):
            self.firstTime = True
            self.active_states.get()
        
        allTransitions = []
        allTransitions.extend(self.timedTransitions["/state_C"])
        allTransitions.extend(self.eventTransitions["/state_C"])
        allTransitions.extend(self.timeBreakpointTransitions["/state_C"])
        allTransitions.extend(self.genBreakpointTransitions["/state_C"])
        allTransitions.extend(self.createdTransitions["/state_C"])
        allTransitions.append(self.stopTransitions["/state_C"])
        allTransitions.append(self.pauseTransitions["/state_C"])
        event = "exit: /state_C"
        for tr in allTransitions:
            if not (tr.enabled_event == None):
                event = (event + (" - " + tr.enabled_event.name))
        allAttTuples = []
        allAttTuples.append(["counter", self.counter])
        self.saveEvent(event, self.getSimulatedTime(), allAttTuples)
    
    def _state_D_enter(self):
        self.current_state = self.states["/state_D"]
        self.startTime = self.getSimulatedTime()
        
        while (not self.didCalcs.empty()):
            self.didCalcs.get()
        
        if self.firstTime == True:
            self.localExecutionTime = 0.0
            self.active_states.put(self.current_state)
            
            self.increment_counter();
            
            self.print_internal_state("/state_D")
            event = "entry: /state_D"
            allAttTuples = []
            allAttTuples.append(["counter", self.counter])
            self.saveEvent(event, self.getSimulatedTime(), allAttTuples)
            print((colors.fg.lightgreen + "Available Transition Options:") + colors.reset)
            self.process_event_transitions("/state_D")
            
            print(colors.fg.lightgrey +"[/state_D] > "+colors.reset),
        else:
            event = "re-entry: /state_D"
            allAttTuples = []
            allAttTuples.append(["counter", self.counter])
            self.saveEvent(event, self.getSimulatedTime(), allAttTuples)
            print(colors.fg.lightgrey +"[/state_D] > "+colors.reset),
    
    def _state_D_exit(self):
        index = 2
        for et in self.expiredTimestamps:
            self.removeTimer(index)
            index = (index + 1)
        
        if self.didCalcs.empty():
            self.localExecutionTime = (self.localExecutionTime + (self.getSimulatedTime() - self.startTime))
            self.executionTime = (self.executionTime + (self.getSimulatedTime() - self.startTime))
            self.didCalcs.put(True)
        
        found = False
        for b in self.timeBreakpointTransitions["/state_D"]:
            if b.enabled_event != None:
                found = True
                timerIndex = int(b.enabled_event.name[1:2])
                startingIndex = 2
                self.expiredTimestamps[timerIndex - startingIndex] = True
        
        for b in self.genBreakpointTransitions["/state_D"]:
            if b.enabled_event != None:
                found = True
        
        if (self.pauseTransitions["/state_D"].enabled_event == None) and (not found):
            self.firstTime = True
            self.active_states.get()
        
        allTransitions = []
        allTransitions.extend(self.timedTransitions["/state_D"])
        allTransitions.extend(self.eventTransitions["/state_D"])
        allTransitions.extend(self.timeBreakpointTransitions["/state_D"])
        allTransitions.extend(self.genBreakpointTransitions["/state_D"])
        allTransitions.extend(self.createdTransitions["/state_D"])
        allTransitions.append(self.stopTransitions["/state_D"])
        allTransitions.append(self.pauseTransitions["/state_D"])
        event = "exit: /state_D"
        for tr in allTransitions:
            if not (tr.enabled_event == None):
                event = (event + (" - " + tr.enabled_event.name))
        allAttTuples = []
        allAttTuples.append(["counter", self.counter])
        self.saveEvent(event, self.getSimulatedTime(), allAttTuples)
    
    def _state_Debug_enter(self):
        if self.firstTime:
            self.firstTime = False
        targets = list(self.active_states.queue)
        states_names = [s.name for s in targets]
        
        print(colors.fg.lightred),
        print("DEBUG MODE")
        print("Current States: {}".format(states_names))
        print("counter" + ": {}".format(self.counter))
        print(colors.reset),
        print(colors.fg.lightgrey +"[/state_Debug] > "+colors.reset),
    
    def _state_Debug_exit(self):
        self.cumulativeDebugTime = (self.getSimulatedTime() - self.executionTime)
        targets = list(self.active_states.queue)
        for t in targets:
            self.pauseTransitions[t.name].enabled_event = None
    
    def _state_Final_enter(self):
        outputName = "executionTrace.txt"
        self.controller.stop()
        self.saveExecutionTrace(outputName)
        exit(1)
    
    def process_time_transitions(self, timers, state_name):
        iteration = 0
        chosen = None
        lowest = timers[0]
        for t in self.timedTransitions[state_name]:
            if lowest >= timers[iteration]:
                lowest = timers[iteration]
                chosen = t
            iteration = iteration + 1
        if iteration > 0:
            temp = Transition(self, chosen.source, chosen.targets)
            temp.setTrigger(Event("step", self.getInPortName("input")))
            if not self.listContains(self.createdTransitions[state_name], temp):
                self.createdTransitions[state_name].append(temp)
                chosen.source.addTransition(temp)
            attrs = [s.name for s in chosen.targets]
            print((colors.fg.lightgreen + "[time-based]" + colors.fg.lightgrey +" type " + colors.fg.pink +"step" + colors.fg.lightgrey + " to skip the transition to "+ colors.fg.cyan +"{}" + colors.fg.lightgrey +" with a duration of " + colors.fg.pink + "{}" + colors.fg.lightgrey +" seconds" + colors.reset).format(attrs, lowest))
    
    def process_event_transitions(self, state_name):
        possibleT = self.eventTransitions[state_name]
        source = self.current_state
        i = 0
        for t in possibleT:
            temp = Transition(self, source, t.targets)
            name = ("step" + str(i))
            temp.setTrigger(Event(name, self.getInPortName("input")))
            if not self.listContains(self.createdTransitions[state_name], temp):
                self.createdTransitions[state_name].append(temp)
                source.addTransition(temp)
            attrs = [s.name for s in t.targets]
            print((colors.fg.lightgreen + "[event-based]"  + colors.fg.lightgrey +" type " + colors.fg.pink +"{}"+ colors.fg.lightgrey + " to move to "+ colors.fg.cyan + "{}" + colors.fg.lightgrey +" and simulate event "+ colors.fg.pink + "{}"+ colors.reset).format(name, attrs, t.trigger.name))
            i = (i + 1)
    
    def print_internal_state(self, state_name):
        print("\n" + (colors.fg.cyan + state_name))
        print(colors.fg.cyan + "counter" + (": {}" + colors.reset).format(self.counter))
    
    def saveExecutionTrace(self, outputName):
        currDir = os.getcwd()
        for entry in os.listdir(currDir):
            if os.path.isfile(os.path.join(currDir, entry)) and entry == outputName:
                outputName = outputName + "_1"
        
        simTime = "Total Simulation Time: " + str(float(self.getSimulatedTime())) + " ms (includes Debug Time)"
        exTime = "Execution Time: " + str(self.executionTime) + " ms"
        debugTime = "Total Debug Time: " + str(self.cumulativeDebugTime) + " ms"
        
        f = FileWriter(outputName)
        f.write("Execution Info")
        f.write("")
        f.write(simTime)
        f.write(exTime)
        f.write(debugTime)
        f.write("")
        f.write("Events")
        for ide, event in enumerate(self.tracedEvents):
            eventName = event.getEventName()
            timestamp = event.getTimestamp()
            attributeValues = ""
            for v in event.getAttributeValues():
                attributeValues += v[0] + ": " + str(v[1]) + "; "
            eventInfo = str(ide) + ". Timestamp: " + str(timestamp) +  "; Name: " + eventName + ";  Attributes: ["  + attributeValues + "]"
            # print(ide)
            # print(eventName)
            f.write(eventInfo)
        f.close() 
    
    def saveEvent(self, event_name, timestamp, attribute_values):
        self.tracedEvents.append(TracedEvent(event_name, timestamp, attribute_values))
    
    def listContains(self, transitions, newTransition):
        flag = False
        for t in transitions:
            if ((((t.source == newTransition.source) and (t.targets == newTransition.targets)) and (t.trigger.name == newTransition.trigger.name)) and (t.trigger.port == newTransition.trigger.port)) and (t.action == newTransition.action):
                flag = True
        return flag
    
    def continueGuard_state_A(self, parameters):
        return list(self.active_states.queue) == self.states["/state_A"]
    
    def continueGuard_state_B(self, parameters):
        return list(self.active_states.queue) == self.states["/state_B"]
    
    def continueGuard_state_C(self, parameters):
        return list(self.active_states.queue) == self.states["/state_C"]
    
    def continueGuard_state_D(self, parameters):
        return list(self.active_states.queue) == self.states["/state_D"]
    
    def initializeStatechart(self):
        # enter default state
        event = "start"
        allAttTuples = []
        allAttTuples.append(["counter", self.counter])
        self.saveEvent(event, self.getSimulatedTime(), allAttTuples)
        self.default_targets = self.states["/state_A"].getEffectiveTargetStates()
        RuntimeClassBase.initializeStatechart(self)

class ObjectManager(ObjectManagerBase):
    def __init__(self, controller):
        ObjectManagerBase.__init__(self, controller)
    
    def instantiate(self, class_name, construct_params):
        if class_name == "MainApp":
            instance = MainApp(self.controller)
            instance.associations = {}
        else:
            raise Exception("Cannot instantiate class " + class_name)
        return instance

class Controller(ThreadsControllerBase):
    def __init__(self, keep_running = None, behind_schedule_callback = None):
        if keep_running == None: keep_running = True
        if behind_schedule_callback == None: behind_schedule_callback = None
        ThreadsControllerBase.__init__(self, ObjectManager(self), keep_running, behind_schedule_callback)
        self.addInputPort("input")
        self.addOutputPort("output")
        self.object_manager.createInstance("MainApp", [])